name: Release Build
on:
  push:
    tags:
      - 'v*'
      - 'r*'
jobs:
  cd-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Setup JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 11

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
          
      - name: Build release APK
        run: ./gradlew assembleRelease
        
      - name: Deploy to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{secrets.FIREBASE_APP_ID}}
          token: ${{secrets.FIREBASE_CI_TOKEN}}
          groups: icec_team
          file: app/build/outputs/apk/release/app-release.apk
